name: Deploy Notebook

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
           python-version: 3.8
      
      - name: install requirements
        run: |
          python3 -m pip install ipykernel
          python3 -m ipykernel install --user --name data-science
          python3 -m pip install -r requirements.txt

      - name: build
        run: jupyter-book build .
          
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
