name: Deploy Notebook

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: | 
          python3 -m pip install ipykernel
          python3 -m ipykernel install --user
          pip install -r requirements.txt
          pip install nbconvert
          jupyter nbconvert --to html --output-dir ./docs --output index.html GTFS.ipynb --ExecutePreprocessor.kernel_name=python --ExecutePreprocessor.enabled=True
          
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
